-- CRIAÇÃO DA TABELA "USER"
CREATE TABLE USER_APP
(
    ID       SERIAL PRIMARY KEY,
    USERNAME VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE     VARCHAR(20)  NOT NULL, -- ENUM: USER, ADMIN
    ENABLED  BOOLEAN DEFAULT TRUE
);

-- CRIAÇÃO DA TABELA "TOKEN"
CREATE TABLE TOKEN
(
    ID      SERIAL PRIMARY KEY,
    TOKEN   TEXT    NOT NULL UNIQUE,
    REVOKED BOOLEAN DEFAULT FALSE,
    EXPIRED BOOLEAN DEFAULT FALSE,
    USER_ID INTEGER NOT NULL,
    CONSTRAINT FK_TOKEN_USER FOREIGN KEY (USER_ID) REFERENCES USER_APP (ID) ON DELETE CASCADE
);

CREATE TABLE CIDADE
(
    CID_ID   SERIAL PRIMARY KEY,
    CID_NOME VARCHAR(200),
    CID_UF   CHAR(2)
);

CREATE TABLE ENDERECO
(
    END_ID              SERIAL PRIMARY KEY,
    END_TIPO_LOGRADOURO VARCHAR(50),
    END_LOGRADOURO      VARCHAR(200),
    END_NUMERO          INT,
    END_BAIRRO          VARCHAR(100),
    CID_ID              INT REFERENCES CIDADE (CID_ID)
);

CREATE TABLE PESSOA
(
    PES_ID              SERIAL PRIMARY KEY,
    PES_NOME            VARCHAR(200),
    PES_DATA_NASCIMENTO DATE,
    PES_SEXO            VARCHAR(9),
    PES_MAE             VARCHAR(200),
    PES_PAI             VARCHAR(200)
);

CREATE TABLE UNIDADE
(
    UNID_ID    SERIAL PRIMARY KEY,
    UNID_NOME  VARCHAR(200),
    UNID_SIGLA VARCHAR(20)
);

CREATE TABLE FOTO_PESSOA
(
    FP_ID     SERIAL PRIMARY KEY,
    PES_ID    INT REFERENCES PESSOA (PES_ID),
    FP_DATA   DATE,
    FP_BUCKET VARCHAR(50),
    FP_HASH   VARCHAR(50)
);

CREATE TABLE PESSOA_ENDERECO
(
    PES_ID INT REFERENCES PESSOA (PES_ID),
    END_ID INT REFERENCES ENDERECO (END_ID),
    PRIMARY KEY (PES_ID, END_ID)
);

CREATE TABLE SERVIDOR_TEMPORARIO
(
    PES_ID           INT PRIMARY KEY REFERENCES PESSOA (PES_ID),
    ST_DATA_ADMISSAO DATE,
    ST_DATA_DEMISSAO DATE
);

CREATE TABLE SERVIDOR_EFETIVO
(
    PES_ID       INT PRIMARY KEY REFERENCES PESSOA (PES_ID),
    SE_MATRICULA VARCHAR(20)
);

CREATE TABLE LOTACAO
(
    LOT_ID           SERIAL PRIMARY KEY,
    PES_ID           INT REFERENCES PESSOA (PES_ID),
    UNID_ID          INT REFERENCES UNIDADE (UNID_ID),
    LOT_DATA_LOTACAO DATE,
    LOT_DATA_REMOCAO DATE,
    LOT_PORTARIA     VARCHAR(100)
);

CREATE TABLE UNIDADE_ENDERECO
(
    UNID_ID INT REFERENCES UNIDADE (UNID_ID),
    END_ID  INT REFERENCES ENDERECO (END_ID),
    PRIMARY KEY (UNID_ID, END_ID)
);
